### ISSUE TITLE
Add to .Net 9 support

### ISSUE THREAD

**Issue by Gakki123** [postsharp/Caravela#380]
I'm upgrading my project to . Net9 fails to compile after that
The following error message is displayed:
TargetFramework: net9.0: Attempt to do a numerical comparison of "$(_MaxSupportedLangVersion_MaxSupportedLangVersion)" in condition "'$()' '$(MetalamaMinSupportedLangVersion)'" that evaluates to "" instead of a number. C:Users/Gakki123/.nuget/packages/metalama.compiler/2024.2.11/tasks/net8.0/Microsoft.CSharp.Core.targets

The latest version on Nuget is "2025.0.4-preview", and this version has no dependencies on . Net9

**Comment by Gakki123** [comment]
![PixPin_2024-11-14_09-11-23](https://github.com/user-attachments/assets/b6810d5d-757f-4910-ac5b-c27011c39e0f)

**Comment by prochan2** [comment]
Despite not having any dependecies on .NET 9, Metalama 2025.0 does support .NET 9. Please update to the latest preview for .NET 9 support. Release candidate will be published soon. GA is planned for January 2025.
