### ISSUE TITLE
Trim('"') does not build in OverrideMethod

### ISSUE THREAD

**Issue by ekmedinet** [postsharp/Caravela#383]
Hello,

We are trying to strip double quotes from method return value, but getting metalama build error. Sometimes it shows 

![image](https://github.com/user-attachments/assets/dbf26d71-b931-48a1-b926-b4c0d4766234)

And sometimes just reports some error:

![image](https://github.com/user-attachments/assets/fd1ff636-348f-45f9-8bea-b774a9397643)

Using just Trim() works fine, be we need to strip double quotes. We have resorted to using Starts/EndsWith and Substring, but the code is clunky, also curious how come Trim(char) is not supported?

Thanks!

Tested with the latest version 2024.2.30

**Comment by svick** [comment]
Thanks for the report. Metalama has a bug when processing character literals (like `'"'`). You can work around it by expressing the same code differently: `return returnString.Trim((char)0x22);`

I will work on a proper fix and will notify you here when it's released, which should be soon.

**Comment by ekmedinet** [comment]
Thank you for the response and workaround!

**Comment by prochan2** [comment]
This bug has been fixed in Metalama 2024.2.31 and 2025.0.7-rc.
